name: 'Publish hugo result'
description: 'Build and publish file to remote server'
author: 'Dayu <jcoldyu@gmail.com>'
branding:
  name: 'godayu'
inputs:
  PUBLISH-SCRIPT:
    description: 'Publish script'
    required: true
  SERVER-KEY:
    description: 'Remove server private key'
    required: true
  AK:
    description: 'Qiniu ak'
    required: true
  SK:
    description: 'Qiniu sk'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.publish-script }}